### ISSUE TITLE
Plugin does not install

### ISSUE THREAD

**Issue by stuartthomson** [leogr/docker-authz-plugin#1]
Hi,

Thanks for this repo, it has been very helpful in making plugins a bit easier to understand! Unfortunately, the plugin does not seem to install as expected. I followed the readme, and everything went as expected until the step `make install`. I get the following error message:

```
$ make install
docker plugin install stuartthomson/docker-authz-plugin:dev
Error response from daemon: pull access denied for stuartthomson/docker-authz-plugin, repository does not exist or may require 'docker login': denied: requested access to 
the resource is denied
make: *** [Makefile:31: install] Error 1
```

The plugin does seem to be created correctly:

```
$ docker plugin ls
ID                  NAME                                    DESCRIPTION                       ENABLED
1c20ec293825        stuartthomson/docker-authz-plugin:dev   Authorization plugin for Docker   false
17e84a36c7a5        vieux/sshfs:latest                      sshFS plugin for Docker           true
```

Have you got any idea why this might be happening? I'm running this on Windows 10, `Docker version 19.03.8, build afacb8b`

Thanks!

**Comment by leogr** [comment]
Hey @stuartthomson 

Not totally sure since I have not used this for a long time, but it seems to me that:
- `repository does not exist or may require 'docker login'` is not an issue generated by the plugin, but it relates to the fact that the `stuartthomson/docker-authz-plugin` docker image is missing (indeed, I didn't find it [here](https://hub.docker.com/r/stuartthomson/docker-authz-plugin))
- it's installed but not enabled (see `false` under the `ENABLED` column), you have to edit `/etc/docker/daemon.json` and restart docker as explained in the [README](https://github.com/leogr/docker-authz-plugin#usage), to fully enable it.

I hope that helped.

**Comment by stuartthomson** [comment]
Hi @leogr, thanks for getting back to me!

There didn't seem to be anything in the README about pushing the image to Docker hub which is why it can't be seen there, I assume it's possible to use plugins which are installed only locally.

When trying to edit the daemon settings (Docker Desktop for Windows) I got an error which actually broke Docker, I ended up having to do a 'factory reset' to get it back.

![image](https://user-images.githubusercontent.com/1838353/86033961-b1f4dd80-ba31-11ea-9a65-036f44343268.png)

I understand that this repo is not something you're using a lot, so no worries if you want to close this issue.

**Comment by leogr** [comment]
I can't try with Docker Desktop for Windows, but it seems to be a docker configuration problem. 
Anyway, you're are right: it does not need to be pushed to the registry IIRC, although the image needs to be at least in the local docker registry (I'm assuming it's already there).

That being said, I can't see the whole error log since it's a screenshot, so I'm not sure what caused that.

I keep this open and it would be great if you post your resolution once you find it.

**Comment by leogr** [comment]
Have you found any solution?

**Comment by stuartthomson** [comment]
Hi @leogr I never managed to figure it out. It's a while ago I was trying to figure it out, but I seem to remember also seeing [this issue](https://github.com/moby/moby/issues/31723).

I can probably take a look again in the coming days and let you know where I ended up with this.

**Comment by stuartthomson** [comment]
The readme tells me to run `make create`. This seems to go well. I can then run `docker plugin ls` and see:
```
▶ docker plugin ls
ID                  NAME                            DESCRIPTION                       ENABLED
1b005aed1964        leogr/docker-authz-plugin:dev   Authorization plugin for Docker   false
```
The readme then says to run `make install`. This results in the following:

```
▶ make install
docker plugin install leogr/docker-authz-plugin:dev
Error response from daemon: pull access denied for leogr/docker-authz-plugin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:31: install] Error 1
```

I wonder if instead I should do `docker plugin enable leogr/docker-authz-plugin:dev`. Doing this results in:

```
▶ docker plugin enable leogr/docker-authz-plugin:dev
Error response from daemon: Unix socket path "/run/docker/plugins/1b005aed19649921a4733eb4aac8b79e6cfc54743125165be6af631de23cc37c/docker-authz-plugin.sock" is too long
```

If it's relevant I'm on windows, with the following version of Docker:

```
▶ docker --version
Docker version 19.03.12, build 48a66213fe
```

Thanks!

**Comment by jjacob27** [comment]
@stuartthomson / @leogr  - running into this exact same error on "Docker desktop for Windows" running on Hyper-V. Did you manage to fix this issue?

Edit: I tried the same steps on a docker client running on ubuntu. The same error happens.

**Comment by jjacob27** [comment]
I did some additional debugging. 

When I go to `./plugin/rootfs/bin` directory on the linux machine and try to execute the docker-authz-plugin, I get
`FATA[0000] mkdir /run/docker/plugins: permission denied`

Then I execute the same thing using `sudo`, it seems to work.

When I look at doing `sudo docker plugin install ...`, it still does not work. So I am guessing that this is permissions related.

Also if i look at `/run/docker/plugins`, i can see `docker-authz-plugin.sock`. However the `docker plugin enable` seems to be searching at `/run/docker/plugins/<plugin-id>/docker-authz-plugin.sock`, which was not created.

https://github.com/docker/go-plugins-helpers/issues/113

I tried to add linux capabilities to the config.json to see if that helps, it didn't.

**Comment by leogr** [comment]
Hey,

I can confirm the problem and also I have done several fixes into this PR :point_right: #3 

Could you test from this branch https://github.com/leogr/docker-authz-plugin/tree/fix/issue-1 ?
It should work now!

N.B.: instructions have changed, please take a look to the README

**Comment by jjacob27** [comment]
Hi @leogr, I have tested this issue now and it is working on my Linux box. On windows, there appears to be a problem with my environment, and could not test this sufficiently.

Thanks for the fix.

**Comment by leogr** [comment]
Hey everyone,

I merged the PR into master, so re-try using the new code and instructions. BTW, I believe the problems had found here should be fixed now, but I had no chance to test it on Docker for Windows. Feel free to continue the discussion here, or open a new issue if you are still encountering problems.

Thank you'll!
